### PR TITLE
Update to fakerphp/faker

### PR DESCRIPTION
**Pull request by jan-heise**
Since fzaninotto/Faker will not be developed any further you should switch to fakerphp/faker

### CODE REVIEW

**Comment by DavidBadura** [comment]
thank you @jan-heise

**Comment by J5Dev** [comment]
Can this be tagged as a release please...

Still only able to pull the previous version 1.0.0

**Comment by DavidBadura** [comment]
sorry, done with the version 1.1.0

**Comment by J5Dev** [comment]
Thank you, I know dev-master could be used, but our policy is to version lock, so this is great thanks :)

**Pull request merged**
